// Environment variables and secrets supplied via .dev.vars locally and
// Wrangler secrets/vars in deployment. These augment the binding-only `Env`
// generated by `wrangler types` (which cannot infer secret names).
//
// `cloudflare:workers` types its `env` export as `Cloudflare.Env`, so the
// augmentation must target that namespace (the bare global `Env` is augmented
// too for code that references it directly).

interface AppSecrets {
  BETTER_AUTH_SECRET: string
  BETTER_AUTH_URL: string
  // OAuth provider credentials are optional: a provider registers only when its
  // pair is set, so local dev can configure just one.
  GITHUB_CLIENT_ID?: string
  GITHUB_CLIENT_SECRET?: string
  GOOGLE_CLIENT_ID?: string
  GOOGLE_CLIENT_SECRET?: string
}

declare namespace Cloudflare {
  interface Env extends AppSecrets {}
}

interface Env extends AppSecrets {}
